Fix format

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,40 +1,40 @@
 #!/bin/sh
 
 install_items=(
-  vim
-  mc
-  fzf
-  zsh
-  jq
-  dmenu
-  emacs
-  git
-  openssh-server
-  gnome-tweaks
-  curl
-  wget
-  make
-  automake
-  gcc
-  gcc-c++
-  kernel-devel
-  cmake
+    vim
+    mc
+    fzf
+    zsh
+    jq
+    dmenu
+    emacs
+    git
+    openssh-server
+    gnome-tweaks
+    curl
+    wget
+    make
+    automake
+    gcc
+    gcc-c++
+    kernel-devel
+    cmake
 )
 
 symlinks=(
-  .zshrc
-  .zshenv
-  .spacemacs
-  .tmux.conf
-  .vimrc
-  starttmux
-  .gitconfig
-  .gitexcludes
-  .gitignore
-  .irbrc
-  .rspec
-  custom-functions.el
-  todo_file.rb
+    .zshrc
+    .zshenv
+    .spacemacs
+    .tmux.conf
+    .vimrc
+    starttmux
+    .gitconfig
+    .gitexcludes
+    .gitignore
+    .irbrc
+    .rspec
+    custom-functions.el
+    todo_file.rb
 )
 
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
@@ -67,41 +67,41 @@ sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/i
 
 echo "Vundle..."
 if [ ! -d "$HOME/.vim/bundle/Vundle.vim" ]; then
-  git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
+    git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
 fi
 
 echo "Installing Spacemacs..."
 if [ ! -f "$HOME/.spacemacs" ]; then
-  if [ -d "$HOME/.emacs.d" ]; then
-    USER_INPUT2=$(whiptail --inputbox ".emacs.d folder already exists.\n\nShould it be removed?\n\nEnter \"Yes!\" if it should be removed. (ATTENTION! Operation cannot be undone)\n\nIf you choose to not delete the folder, this script will exit and you must move / backup it by yourself." 20 60 3>&1 1>&2 2>&3)
+    if [ -d "$HOME/.emacs.d" ]; then
+        USER_INPUT2=$(whiptail --inputbox ".emacs.d folder already exists.\n\nShould it be removed?\n\nEnter \"Yes!\" if it should be removed. (ATTENTION! Operation cannot be undone)\n\nIf you choose to not delete the folder, this script will exit and you must move / backup it by yourself." 20 60 3>&1 1>&2 2>&3)
 
-    exitstatus=$?
-    echo "User entered " $USER_INPUT2
+        exitstatus=$?
+        echo "User entered " $USER_INPUT2
 
-    if [ "$USER_INPUT" != "Yes!" ]; then
-      echo "Please backup / move .emacs.d. Aborting."
-      exit 1
+        if [ "$USER_INPUT" != "Yes!" ]; then
+            echo "Please backup / move .emacs.d. Aborting."
+            exit 1
+        fi
+
+        rm -rf $HOME/.emacs.d
     fi
 
-    rm -rf $HOME/.emacs.d
-  fi
-
-  git clone https://github.com/syl20bnr/spacemacs $HOME/.emacs.d
+    git clone https://github.com/syl20bnr/spacemacs $HOME/.emacs.d
 else
-  echo "Spacemacs seems to be installed already."
+    echo "Spacemacs seems to be installed already."
 fi
 
 echo "Installing asdf..."
 if [ ! -d "$HOME/.asdf" ]; then
-  git clone https://github.com/asdf-vm/asdf.git $HOME/.asdf --branch v0.7.8
+    git clone https://github.com/asdf-vm/asdf.git $HOME/.asdf --branch v0.7.8
 fi
 
 echo "Creating symlinks..."
 for i in "${symlinks[@]}"
 do
-  if [ ! -f "$HOME/$i" ]; then
-    ln -s "$DIR/$i" "$HOME/$i"
-  fi
+    if [ ! -f "$HOME/$i" ]; then
+        ln -s "$DIR/$i" "$HOME/$i"
+    fi
 done
 
 echo "Done."
